### ISSUE TITLE
is label useless in latexdivs.py?

### ISSUE THREAD

**Issue by chdemko** [ickc/pandoc-amsthm#1]
Do you really need `\label` in https://github.com/ickc/pandoc-amsthm/blob/gh-pages/py/latexdivs.py#L25 since pandoc  generates a `\hypertarget`in LaTeX mode?

~~~
<div id="myid">test</div>

See [here](#myid)
~~~

is rendered in LaTeX as:

~~~
\hypertarget{myid}{}
test

See \protect\hyperlink{myid}{here}
~~~

**Comment by ickc** [comment]
Probably you're right. I was folking the other filter in [pandocfilters/theorem.py at master · jgm/pandocfilters](https://github.com/jgm/pandocfilters/blob/master/examples/theorem.py). But since I folked yours I deprecated that one already. Thanks!
