### ISSUE TITLE
Complete rewrite using panflute

### ISSUE THREAD

**Issue by ickc** [ickc/pandoc-amsthm#15]
In light of issue #12 and #13, both requires a complete rewrite of the templates. Given `@jgm` recommended panflute, and Haskell has a tighter integration (allows the use of `Text.Pandoc.Templates`). It seems pandocfilters should be abandoned.

Either way requires some extra installations. panflute still seems to have a lower barrier since it is a scripting language (and cabal/stack install could be intimidating).

Edit: Todo list:

- [ ] revert 330768e (at least partially): not a good idea to check output format and branching from there. Reason: panflute autofilter calls the main function, and may not pass the arg as the output format.

**Comment by ickc** [comment]
@ctaaronsan, just curious about the fork: are you interested in contributing to the panflute branch?

**Comment by ctaaronsan** [comment]
@ickc Oops! I didn't notice the panflute branch and was just trying to make some minor modification to fit my needs. The panflute branch seems much cleaner though. Is there anything I can help?

**Comment by ickc** [comment]
The current master branch is a legacy. The current planflute branch should be of a much better design, and will take advantage of the native pandoc elements for output other than latex (and get rid of custom templates). currently only the latex output is implemented. A mapping between the pandoc-amsthm syntax to pandoc elements needed to be done. I was planning to do so but got super busy and have to leave it aside. The next window of time for me to work on it will be Spring break (late March).

If you're interested you can read the notes in this issue, and trace back to the issues referred to. The repository also already have the "unit test" written up, meaning that the mapping is already settled, but unimplemented yet.

Feel free to play around and ask me if there's anything not clear.
